// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxKCQymFIfQ113iOO2i9PzZyLROjKlsuU',
    appId: '1:433509203489:web:40aef4d2cd81a3fe272d60',
    messagingSenderId: '433509203489',
    projectId: 'rccg-jp',
    authDomain: 'rccg-jp.firebaseapp.com',
    storageBucket: 'rccg-jp.appspot.com',
    measurementId: 'G-BC7F7PYG0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZl0MvRc4ZHmyb_BJQj1UI1YQ7ya-Kdk',
    appId: '1:433509203489:android:5b7815866f2068dd272d60',
    messagingSenderId: '433509203489',
    projectId: 'rccg-jp',
    storageBucket: 'rccg-jp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuw44B0agvmwRS_dQvmWBVCUwiqVCjT7I',
    appId: '1:433509203489:ios:36e0b21963dc2a33272d60',
    messagingSenderId: '433509203489',
    projectId: 'rccg-jp',
    storageBucket: 'rccg-jp.appspot.com',
    iosBundleId: 'com.partner.rccgJp',
  );
}
